# Generated by Django 5.2.15 on 2026-07-06 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0001_initial'),
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldefinition',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Business line for tenant isolation / 业务线归属', null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam.business', verbose_name='Business'),
        ),
        migrations.AddField(
            model_name='modeldefinition',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='cmdb.classification', verbose_name='所属分类'),
        ),
        migrations.AddField(
            model_name='modelassociation',
            name='source_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_assocs', to='cmdb.modeldefinition', verbose_name='源模型'),
        ),
        migrations.AddField(
            model_name='modelassociation',
            name='target_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tgt_assocs', to='cmdb.modeldefinition', verbose_name='目标模型'),
        ),
        migrations.AddField(
            model_name='mainlinetopo',
            name='model_definition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mainline_topo', to='cmdb.modeldefinition', verbose_name='模型'),
        ),
        migrations.AddField(
            model_name='mainlinetopo',
            name='parent_model',
            field=models.ForeignKey(blank=True, help_text='上一级模型，顶层模型（如 Biz）此字段为空', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cmdb.modeldefinition', verbose_name='父级模型'),
        ),
        migrations.AddField(
            model_name='attributegroup',
            name='model_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_groups', to='cmdb.modeldefinition', verbose_name='所属模型'),
        ),
        migrations.AddField(
            model_name='modelfield',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='cmdb.attributegroup', verbose_name='所属分组'),
        ),
        migrations.AddField(
            model_name='modelfield',
            name='model_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='cmdb.modeldefinition', verbose_name='所属模型'),
        ),
        migrations.AddField(
            model_name='objectunique',
            name='model_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniques', to='cmdb.modeldefinition', verbose_name='所属模型'),
        ),
        migrations.AlterUniqueTogether(
            name='modelassociation',
            unique_together={('source_model', 'target_model', 'association_type')},
        ),
        migrations.AlterUniqueTogether(
            name='attributegroup',
            unique_together={('model_definition', 'group_id')},
        ),
        migrations.AlterUniqueTogether(
            name='modelfield',
            unique_together={('model_definition', 'name')},
        ),
    ]
