# Generated by Django 4.2.7 on 2026-06-04 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDefinition',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=255, verbose_name='作业名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('executor', models.CharField(choices=[('ssh', 'SSH 远程执行'), ('local', '本地执行'), ('ansible', 'Ansible Playbook')], default='ssh', max_length=32, verbose_name='执行方式')),
                ('command', models.TextField(blank=True, help_text='直接填写命令，与脚本二选一', null=True, verbose_name='内联命令')),
                ('params', models.JSONField(default=dict, verbose_name='默认参数')),
                ('timeout_seconds', models.IntegerField(default=300, verbose_name='超时时间(秒)')),
                ('need_approval', models.BooleanField(default=False, verbose_name='需要审批')),
                ('run_as', models.CharField(default='root', max_length=128, verbose_name='执行用户')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '作业定义',
                'verbose_name_plural': '作业定义',
                'db_table': 'dvadmin_job_definition',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=255, verbose_name='脚本名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('script_type', models.CharField(choices=[('shell', 'Shell'), ('python', 'Python'), ('powershell', 'PowerShell'), ('bat', 'Batch'), ('sql', 'SQL')], default='shell', max_length=32, verbose_name='脚本类型')),
                ('content', models.TextField(verbose_name='脚本内容')),
                ('params_schema', models.JSONField(default=dict, help_text='定义脚本参数的 JSON Schema', verbose_name='参数 Schema')),
                ('version', models.CharField(default='1.0', max_length=32, verbose_name='版本')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('is_builtin', models.BooleanField(default=False, verbose_name='是否内置')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '脚本',
                'verbose_name_plural': '脚本',
                'db_table': 'dvadmin_job_script',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='JobExecution',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('timeout', '超时'), ('cancelled', '已取消'), ('approving', '待审批')], default='pending', max_length=32, verbose_name='状态')),
                ('target_hosts', models.JSONField(default=list, help_text='主机 IP 或 CMDB host_id 列表', verbose_name='目标主机')),
                ('params', models.JSONField(default=dict, verbose_name='执行参数')),
                ('result_summary', models.TextField(blank=True, null=True, verbose_name='结果摘要')),
                ('result_detail', models.JSONField(default=dict, verbose_name='详细结果(按主机)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('exit_code', models.IntegerField(blank=True, null=True, verbose_name='退出码')),
                ('executor', models.CharField(default='ssh', max_length=32, verbose_name='执行方式')),
                ('run_as', models.CharField(default='root', max_length=128, verbose_name='执行用户')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='job_platform.jobdefinition', verbose_name='关联作业')),
            ],
            options={
                'verbose_name': '作业执行记录',
                'verbose_name_plural': '作业执行记录',
                'db_table': 'dvadmin_job_execution',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.AddField(
            model_name='jobdefinition',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='job_platform.script', verbose_name='关联脚本'),
        ),
        migrations.CreateModel(
            name='DangerousCmdRule',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=255, verbose_name='规则名称')),
                ('pattern', models.CharField(help_text='关键词或正则表达式', max_length=512, verbose_name='匹配模式')),
                ('is_regex', models.BooleanField(default=False, verbose_name='是否正则')),
                ('action', models.CharField(choices=[('reject', '直接拦截'), ('approval', '需要审批'), ('warn', '仅警告')], default='reject', max_length=32, verbose_name='处理方式')),
                ('severity', models.CharField(default='high', max_length=32, verbose_name='严重级别')),
                ('description', models.TextField(blank=True, null=True, verbose_name='规则说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '高危命令规则',
                'verbose_name_plural': '高危命令规则',
                'db_table': 'dvadmin_job_dangerous_cmd_rule',
                'ordering': ['-create_datetime'],
            },
        ),
    ]
