# Generated by Django 5.2.15 on 2026-07-13 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorDefinition',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('creator', models.IntegerField(blank=True, db_column='creator_id', help_text='创建人', null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('code', models.CharField(help_text='唯一编码，如 aliyun_ecs、wecom', max_length=128, unique=True, verbose_name='编码')),
                ('name', models.CharField(help_text='展示名称，如 阿里云ECS、企业微信', max_length=255, verbose_name='名称')),
                ('category', models.CharField(choices=[('cloud', '云厂商'), ('notification', '通知通道'), ('auth', '认证源'), ('paas', 'PaaS 平台'), ('monitor', '监控系统'), ('ai', 'AI 服务'), ('other', '其他')], default='other', max_length=64, verbose_name='分类')),
                ('version', models.CharField(default='1.0', max_length=32, verbose_name='版本')),
                ('icon', models.CharField(blank=True, max_length=512, null=True, verbose_name='图标 URL')),
                ('config_schema', models.JSONField(default=dict, help_text='定义实例配置字段的表单 schema', verbose_name='配置 JSON Schema')),
                ('provider_class', models.CharField(blank=True, help_text='如 integration.adapters.cloud.aliyun.AliyunConnector', max_length=512, null=True, verbose_name='适配器类路径')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '连接器定义',
                'verbose_name_plural': '连接器定义',
                'db_table': 'opsflow_intg_connector_definition',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorInstance',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('creator', models.IntegerField(blank=True, db_column='creator_id', help_text='创建人', null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(help_text='如 生产环境阿里云、测试环境企微', max_length=255, verbose_name='实例名称')),
                ('config', models.JSONField(default=dict, help_text='region、endpoint 等非敏感配置项', verbose_name='配置（非敏感）')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('error', '异常'), ('unknown', '未知')], default='unknown', max_length=32, verbose_name='状态')),
                ('health_check_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='健康检查地址')),
                ('last_health_check', models.DateTimeField(blank=True, null=True, verbose_name='最后健康检查时间')),
                ('last_health_message', models.TextField(blank=True, null=True, verbose_name='健康检查消息')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('business', models.ForeignKey(blank=True, help_text='Business line for tenant isolation / 业务线归属', null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam.business', verbose_name='Business')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='integration.connectordefinition', verbose_name='所属定义')),
            ],
            options={
                'verbose_name': '连接器实例',
                'verbose_name_plural': '连接器实例',
                'db_table': 'opsflow_intg_connector_instance',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ConnectorCredential',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('creator', models.IntegerField(blank=True, db_column='creator_id', help_text='创建人', null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(help_text='如 阿里云 AK、数据库密码', max_length=255, verbose_name='凭证名称')),
                ('cred_type', models.CharField(choices=[('access_key', 'Access Key + Secret Key'), ('password', '密码'), ('token', 'Token'), ('certificate', '证书'), ('custom', '自定义')], default='access_key', max_length=64, verbose_name='凭证类型')),
                ('encrypted_value', models.TextField(help_text='AES-256 加密存储', verbose_name='加密后的凭证值')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='integration.connectorinstance', verbose_name='所属实例')),
            ],
            options={
                'verbose_name': '连接器凭证',
                'verbose_name_plural': '连接器凭证',
                'db_table': 'opsflow_intg_connector_credential',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('creator', models.IntegerField(blank=True, db_column='creator_id', help_text='创建人', null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('definition_code', models.CharField(blank=True, max_length=128, null=True, verbose_name='定义编码（快照）')),
                ('action', models.CharField(help_text='如 describe_instances、send_sms', max_length=255, verbose_name='操作')),
                ('request_data', models.JSONField(default=dict, verbose_name='请求参数')),
                ('response_data', models.JSONField(default=dict, verbose_name='返回数据')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('timeout', '超时'), ('error', '异常')], default='success', max_length=32, verbose_name='调用状态')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('source_app', models.CharField(blank=True, max_length=128, null=True, verbose_name='调用来源模块')),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True, verbose_name='请求 IP')),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='integration.connectorinstance', verbose_name='连接器实例')),
            ],
            options={
                'verbose_name': '集成调用日志',
                'verbose_name_plural': '集成调用日志',
                'db_table': 'opsflow_intg_integration_log',
                'ordering': ['-create_datetime'],
            },
        ),
    ]
