# Generated by Django 5.2.15 on 2026-07-03 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiApp',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('creator', models.IntegerField(blank=True, db_column='creator_id', help_text='创建人', null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=255, verbose_name='应用名称')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='所属公司')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('contact_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='联系人')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='联系邮箱')),
                ('status', models.CharField(choices=[('active', '活跃'), ('disabled', '已禁用'), ('expired', '已过期')], default='active', max_length=32, verbose_name='状态')),
                ('rate_limit', models.IntegerField(default=100, help_text='每秒请求数', verbose_name='频率限制(QPS)')),
                ('allowed_apis', models.JSONField(default=list, help_text='API 路径前缀列表，空表示全部允许', verbose_name='允许的 API 列表')),
                ('allowed_ips', models.JSONField(default=list, verbose_name='IP 白名单')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '第三方应用',
                'verbose_name_plural': '第三方应用',
                'db_table': 'opsflow_open_api_app',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='OpenApiToken',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('creator', models.IntegerField(blank=True, db_column='creator_id', help_text='创建人', null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('access_key', models.CharField(max_length=64, unique=True, verbose_name='Access Key')),
                ('secret_key', models.CharField(max_length=128, verbose_name='Secret Key (加密存储)')),
                ('status', models.CharField(choices=[('active', '有效'), ('revoked', '已吊销'), ('expired', '已过期')], default='active', max_length=32, verbose_name='状态')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='描述')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='open_api.apiapp', verbose_name='所属应用')),
            ],
            options={
                'verbose_name': 'API 凭证',
                'verbose_name_plural': 'API 凭证',
                'db_table': 'opsflow_open_api_token',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='OpenApiLog',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('creator', models.IntegerField(blank=True, db_column='creator_id', help_text='创建人', null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('request_path', models.CharField(max_length=512, verbose_name='请求路径')),
                ('request_method', models.CharField(max_length=16, verbose_name='请求方法')),
                ('request_params', models.JSONField(default=dict, verbose_name='请求参数')),
                ('response_status', models.IntegerField(default=200, verbose_name='响应状态码')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True, verbose_name='请求 IP')),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True, verbose_name='User-Agent')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to='open_api.apiapp', verbose_name='调用应用')),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='open_api.openapitoken', verbose_name='使用凭证')),
            ],
            options={
                'verbose_name': 'API 调用日志',
                'verbose_name_plural': 'API 调用日志',
                'db_table': 'opsflow_open_api_log',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='WebhookSubscription',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('creator', models.IntegerField(blank=True, db_column='creator_id', help_text='创建人', null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=255, verbose_name='订阅名称')),
                ('event_type', models.CharField(choices=[('incident.created', '事件工单创建'), ('incident.updated', '事件工单更新'), ('incident.resolved', '事件工单解决'), ('alert.firing', '告警触发'), ('alert.resolved', '告警恢复'), ('job.completed', '作业完成'), ('execution.completed', '流程完成')], max_length=128, verbose_name='事件类型')),
                ('callback_url', models.URLField(max_length=1024, verbose_name='回调地址')),
                ('secret', models.CharField(blank=True, help_text='用于 HMAC 签名验证', max_length=255, null=True, verbose_name='签名密钥')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('retry_count', models.IntegerField(default=3, verbose_name='重试次数')),
                ('retry_interval', models.IntegerField(default=60, verbose_name='重试间隔(秒)')),
                ('last_delivery_at', models.DateTimeField(blank=True, null=True, verbose_name='最后投递时间')),
                ('last_delivery_status', models.CharField(default='pending', max_length=32, verbose_name='最后投递状态')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='open_api.apiapp', verbose_name='所属应用')),
            ],
            options={
                'verbose_name': '事件订阅',
                'verbose_name_plural': '事件订阅',
                'db_table': 'opsflow_open_api_webhook',
                'ordering': ['-create_datetime'],
            },
        ),
    ]
