---
- name: 执行 Shell 命令
  ansible.builtin.shell: "{{ command }}"
  args:
    chdir: "{{ working_dir | default(omit) }}"
  register: _shell_result
  ignore_errors: true

- name: 输出执行结果
  ansible.builtin.set_fact:
    stdout: "{{ _shell_result.stdout | default('') }}"
    stderr: "{{ _shell_result.stderr | default('') }}"
    returncode: "{{ _shell_result.rc | default(-1) }}"
