---
- name: 控制系统服务
  ansible.builtin.systemd:
    name: "{{ service }}"
    state: "{{ action | default('started') }}"
    enabled: "{{ enabled | default(false) | bool }}"
  register: _service_result

- name: 输出服务控制结果
  ansible.builtin.set_fact:
    changed: "{{ _service_result.changed }}"
    status: "{{ _service_result.status | default('') }}"
