# Generated by Django 5.2.15 on 2026-07-03 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('fault_pattern', 'Fault Pattern'), ('ops_experience', 'Operations Experience'), ('team_preference', 'Team Preference'), ('temporary_constraint', 'Temporary Constraint')], max_length=32)),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('tags_json', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ops_memory',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'prod-k8s-cluster'", max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('env_type', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('canary', 'Canary'), ('development', 'Development')], default='development', max_length=16)),
                ('topology_json', models.JSONField(default=dict, help_text='CMDB-injected topology')),
                ('constraints_md', models.TextField(blank=True, help_text='Markdown constraints (change windows, rules)')),
                ('credential_ref', models.CharField(blank=True, help_text='Vault path or key reference', max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ops_environment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('operator', models.CharField(default='admin', max_length=128)),
                ('mode', models.CharField(choices=[('repl', 'REPL'), ('oneshot', 'One-shot')], max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('aborted', 'Aborted')], default='active', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('user_input', models.TextField(blank=True, help_text="User's original input text")),
                ('result_json', models.JSONField(blank=True, default=dict, help_text='Full execution result (tool_calls, final output, timeline)')),
                ('task_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Execution status for async polling', max_length=16)),
                ('business', models.ForeignKey(blank=True, help_text='Business line for tenant isolation / 业务线归属', null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam.business', verbose_name='Business')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='opsagent.environmentcontext')),
            ],
            options={
                'db_table': 'ops_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('target', models.CharField(blank=True, help_text='Target resource identifier', max_length=256)),
                ('tool_name', models.CharField(max_length=128)),
                ('parameters_json', models.JSONField(default=dict)),
                ('risk_operation', models.CharField(choices=[('READ', 'Read'), ('LOW_WRITE', 'Low Write'), ('MEDIUM_WRITE', 'Medium Write'), ('HIGH_WRITE', 'High Write'), ('CRITICAL', 'Critical')], max_length=16)),
                ('risk_environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('canary', 'Canary'), ('production', 'Production')], max_length=16)),
                ('risk_blast_radius', models.CharField(choices=[('single', 'Single'), ('group', 'Group'), ('cluster-wide', 'Cluster-Wide')], max_length=32)),
                ('risk_score', models.FloatField()),
                ('safety_decision', models.CharField(choices=[('AUTO', 'Auto'), ('AUTO_ECHO', 'Auto Echo'), ('ASK', 'Ask'), ('ASK_BLAST', 'Ask Blast'), ('DENY', 'Deny')], max_length=16)),
                ('approved_by', models.CharField(blank=True, max_length=128)),
                ('approval_time_ms', models.PositiveIntegerField(null=True)),
                ('execution_started', models.DateTimeField(null=True)),
                ('execution_completed', models.DateTimeField(null=True)),
                ('execution_duration_ms', models.PositiveIntegerField(null=True)),
                ('execution_success', models.BooleanField(null=True)),
                ('result_summary', models.TextField(blank=True)),
                ('llm_reasoning', models.TextField(blank=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_records', to='opsagent.session')),
            ],
            options={
                'db_table': 'ops_audit',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['session', 'seq'], name='ops_audit_session_a9082b_idx'), models.Index(fields=['target', 'timestamp'], name='ops_audit_target_7e76d9_idx'), models.Index(fields=['tool_name', 'timestamp'], name='ops_audit_tool_na_1190c2_idx'), models.Index(fields=['risk_score'], name='ops_audit_risk_sc_cbc22b_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'seq'), name='uq_audit_session_seq')],
            },
        ),
    ]
