# Generated by Django 5.2.15 on 2026-07-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalationlevel',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='级别名称(英文)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='分类名称(英文)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='服务描述(英文)'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='服务名称(英文)'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='策略名称(英文)'),
        ),
        migrations.AddField(
            model_name='state',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='节点名称(英文)'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='流程名称(英文)'),
        ),
    ]
