# Generated by Django 5.2.15 on 2026-07-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm', '0002_escalationlevel_name_en_servicecategory_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowversion',
            name='pipeline_tree',
            field=models.JSONField(default=dict, verbose_name='流程图画布数据 (对齐 Opsflow)'),
        ),
    ]
