# Generated by Django 5.2.15 on 2026-07-03 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iam', '0001_initial'),
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deptmapping',
            name='source_instance',
            field=models.ForeignKey(db_constraint=False, help_text='集成中心的连接器实例 / ConnectorInstance in Integration Hub', on_delete=django.db.models.deletion.CASCADE, related_name='dept_mappings', to='integration.connectorinstance', verbose_name='Source Instance'),
        ),
        migrations.AddField(
            model_name='iamdept',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, help_text='上级部门', null=True, on_delete=django.db.models.deletion.CASCADE, to='iam.iamdept', verbose_name='上级部门'),
        ),
        migrations.AddField(
            model_name='deptmapping',
            name='dept',
            field=models.ForeignKey(db_constraint=False, help_text='本地的系统部门 / Local department record', on_delete=django.db.models.deletion.CASCADE, related_name='sync_mappings', to='iam.iamdept', verbose_name='Local Dept'),
        ),
        migrations.AddField(
            model_name='iamusers',
            name='dept',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='关联部门', null=True, on_delete=django.db.models.deletion.PROTECT, to='iam.iamdept', verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='iamrolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='iam.iampermission', verbose_name='权限'),
        ),
        migrations.AddField(
            model_name='iamrolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='iam.iamrole', verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='iamuserrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='iam.iamrole', verbose_name='角色'),
        ),
        migrations.AlterUniqueTogether(
            name='pagetab',
            unique_together={('app', 'key')},
        ),
        migrations.AddField(
            model_name='pagebutton',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='iam.pagetab', verbose_name='归属 Tab'),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='target_iam_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_requests', to='iam.iamrole', verbose_name='目标统一角色'),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='target_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam.iammenu', verbose_name='目标菜单'),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AddField(
            model_name='project',
            name='business',
            field=models.ForeignKey(blank=True, help_text='所属业务线 / Parent business line. null for backward compatibility.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='iam.business', verbose_name='Business'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='项目负责人 / Project owner', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='permissionrequest',
            name='target_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam.project', verbose_name='目标项目'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(help_text='所属项目 / Parent project', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='iam.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='user',
            field=models.ForeignKey(help_text='用户 / Member user', on_delete=django.db.models.deletion.CASCADE, related_name='iam_project_members', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='roletemplate',
            name='source_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='iam.iamrole', verbose_name='来源角色'),
        ),
        migrations.AddField(
            model_name='userdirectpermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='授权人'),
        ),
        migrations.AddField(
            model_name='userdirectpermission',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iam.iammenu', verbose_name='直接授权菜单'),
        ),
        migrations.AddField(
            model_name='userdirectpermission',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iam.iampermission', verbose_name='直接授权权限'),
        ),
        migrations.AddField(
            model_name='userdirectpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_permissions', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='usermapping',
            name='source_instance',
            field=models.ForeignKey(db_constraint=False, help_text='集成中心的连接器实例 / ConnectorInstance in Integration Hub', on_delete=django.db.models.deletion.CASCADE, related_name='user_mappings', to='integration.connectorinstance', verbose_name='Source Instance'),
        ),
        migrations.AddField(
            model_name='usermapping',
            name='user',
            field=models.ForeignKey(db_constraint=False, help_text='本地的系统用户 / Local user record', on_delete=django.db.models.deletion.CASCADE, related_name='sync_mappings', to=settings.AUTH_USER_MODEL, verbose_name='Local User'),
        ),
        migrations.AlterUniqueTogether(
            name='businessmember',
            unique_together={('business', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='deployenvironmentpermission',
            unique_together={('user', 'environment')},
        ),
        migrations.AddIndex(
            model_name='deptmapping',
            index=models.Index(fields=['source_instance', 'remote_dn'], name='opsflow_iam_source__ded1bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deptmapping',
            unique_together={('source_instance', 'remote_dn')},
        ),
        migrations.AlterUniqueTogether(
            name='iamrolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AlterUniqueTogether(
            name='iamuserrole',
            unique_together={('user', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='pagebutton',
            unique_together={('tab', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('project', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='userdirectpermission',
            unique_together={('user', 'menu'), ('user', 'permission')},
        ),
        migrations.AddIndex(
            model_name='usermapping',
            index=models.Index(fields=['source_instance', 'remote_dn'], name='opsflow_iam_source__2ac24a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermapping',
            unique_together={('source_instance', 'remote_dn')},
        ),
    ]
