"""
Django settings for application project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ================================================= #
# ******************** 环境配置 ******************** #
# ================================================= #
from conf.env import *

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure--z8%exyzt7e_%i@1+#1mm=%lb5=^fx_57=1@a+_y7bg5-w%)sm"
# 初始化plugins插件路径到环境变量中
PLUGINS_PATH = os.path.join(BASE_DIR, "plugins")
sys.path.insert(0, os.path.join(PLUGINS_PATH))
[
    sys.path.insert(0, os.path.join(PLUGINS_PATH, ele))
    for ele in os.listdir(PLUGINS_PATH)
    if os.path.isdir(os.path.join(PLUGINS_PATH, ele)) and not ele.startswith("__")
]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = locals().get("DEBUG", True)
ALLOWED_HOSTS = ['*']

# 列权限需要排除的App应用
COLUMN_EXCLUDE_APPS = ['channels', 'captcha'] + locals().get("COLUMN_EXCLUDE_APPS", [])

# ================================================= #
# ******************** App 注册 ******************* #
# ================================================= #
INSTALLED_APPS = [
    "simpleui",
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_comment_migrate",
    "rest_framework",
    "django_filters",
    "corsheaders",  # 注册跨域app
    "drf_spectacular",
    "captcha",
    "channels",
    "django_apscheduler",
    "django_extensions",
    "dvadmin.system",
    "opsagent",
    # ------------------------------------------------------------------ #
    #  OpsFlow Pipeline 引擎 (bamboo-pipeline)                            #
    # ------------------------------------------------------------------ #
    "pipeline.component_framework",
    "pipeline.eri",
    "pipeline.contrib.rollback",
    "pipeline.contrib.engine_admin",
    "opsflow",
    "iam",
    "integration",
    "cmdb",
    "itsm",
    "monitor",
    "job_platform",
    "portal",
    "open_api",
    "common",
    "mock_service",
]

# ================================================= #
# ******************** 骨架配置 ******************* #
# ================================================= #
MIDDLEWARE = [
    "dvadmin.utils.middleware.HealthCheckMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",  # i18n 语言检测
    "corsheaders.middleware.CorsMiddleware",  # 跨域中间件
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "dvadmin.utils.middleware.ApiLoggingMiddleware",
]

ROOT_URLCONF = "application.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "application.wsgi.application"

AUTH_USER_MODEL = "system.Users"
USERNAME_FIELD = "username"

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ================================================= #
# ****************** 国际化 *********************** #
# ================================================= #
LANGUAGE_CODE = "zh-hans"
LANGUAGES = [
    ('zh-hans', '简体中文'),
    ('en', 'English'),
]
LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]
TIME_ZONE = "Asia/Shanghai"
USE_I18N = True
USE_TZ = True

# ================================================= #
# ****************** 静态文件 ********************* #
# ================================================= #
STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
MEDIA_ROOT = "media"
MEDIA_URL = "/media/"
STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
)

# ================================================= #
# ****************** 组件配置 ********************* #
# ================================================= #
from application.components.database import *
from application.components.channels import *
from application.components.logging import *
from application.components.rest_framework import *
from application.components.auth import *
from application.components.cors_security import *
from application.components.monitor_adapters import *
from application.components.celery import *
from application.components.pipeline import *

# ================================================= #
# ****************** 杂项配置 ********************* #
# ================================================= #
DEFAULT_AUTO_FIELD = "django.db.models.AutoField"
API_LOG_ENABLE = True
API_LOG_METHODS = ["POST", "UPDATE", "DELETE", "PUT"]
API_MODEL_MAP = {
    "/token/": "登录模块",
    "/api/login/": "登录模块",
    "/api/plugins_market/plugins/": "插件市场",
}

STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

ALL_MODELS_OBJECTS = []
INITIALIZE_LIST = []
INITIALIZE_RESET_LIST = []
TABLE_PREFIX = locals().get('TABLE_PREFIX', "")
SYSTEM_CONFIG = {}
DICTIONARY_CONFIG = {}

# # ================================================= #
# # ******************** 插件配置 ******************** #
# # ================================================= #
# TENANT_SHARED_APPS = []
PLUGINS_URL_PATTERNS = []

