# Generated by Django 5.2.15 on 2026-07-06 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('iam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecenter',
            name='target_dept',
            field=models.ManyToManyField(blank=True, db_constraint=False, help_text='目标部门', to='iam.iamdept', verbose_name='目标部门'),
        ),
        migrations.AddField(
            model_name='messagecenter',
            name='target_role',
            field=models.ManyToManyField(blank=True, db_constraint=False, help_text='目标角色', to='iam.iamrole', verbose_name='目标角色'),
        ),
        migrations.AddField(
            model_name='messagecentertargetuser',
            name='messagecenter',
            field=models.ForeignKey(db_constraint=False, help_text='关联消息中心表', on_delete=django.db.models.deletion.CASCADE, to='common.messagecenter', verbose_name='关联消息中心表'),
        ),
        migrations.AddField(
            model_name='messagecentertargetuser',
            name='users',
            field=models.ForeignKey(db_constraint=False, help_text='关联用户表', on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to=settings.AUTH_USER_MODEL, verbose_name='关联用户表'),
        ),
        migrations.AddField(
            model_name='messagecenter',
            name='target_user',
            field=models.ManyToManyField(blank=True, help_text='目标用户', related_name='user', through='common.MessageCenterTargetUser', through_fields=('messagecenter', 'users'), to=settings.AUTH_USER_MODEL, verbose_name='目标用户'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='父级', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.systemconfig', verbose_name='父级'),
        ),
        migrations.AlterUniqueTogether(
            name='systemconfig',
            unique_together={('key', 'parent_id')},
        ),
    ]
