# Generated by Django 4.2.7 on 2026-06-04 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itsm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorTarget',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=255, verbose_name='目标名称')),
                ('target_type', models.CharField(choices=[('host', '主机'), ('service', '服务'), ('network', '网络设备'), ('middleware', '中间件'), ('custom', '自定义')], default='host', max_length=64, verbose_name='目标类型')),
                ('endpoint', models.CharField(help_text='如 http://192.168.1.1:9090/metrics', max_length=512, verbose_name='采集端点')),
                ('source', models.CharField(default='prometheus', help_text='prometheus / influxdb / telegraf', max_length=64, verbose_name='数据源')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('cmdb_host_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='关联 CMDB 主机 ID')),
                ('labels', models.JSONField(default=dict, verbose_name='标签')),
                ('extra_config', models.JSONField(default=dict, verbose_name='额外配置')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '监控目标',
                'verbose_name_plural': '监控目标',
                'db_table': 'dvadmin_monitor_target',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=255, verbose_name='规则名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('severity', models.CharField(choices=[('critical', '严重'), ('warning', '警告'), ('info', '信息')], default='warning', max_length=32, verbose_name='严重级别')),
                ('status', models.CharField(choices=[('enabled', '启用'), ('disabled', '禁用')], default='enabled', max_length=32, verbose_name='状态')),
                ('condition_expr', models.TextField(help_text='如 cpu_usage > 90 持续 5 分钟', verbose_name='告警条件表达式')),
                ('duration_seconds', models.IntegerField(default=300, verbose_name='持续时长(秒)')),
                ('silence_seconds', models.IntegerField(default=3600, verbose_name='静默时长(秒)')),
                ('auto_resolve_seconds', models.IntegerField(default=0, help_text='0 表示不自动恢复', verbose_name='自动恢复时长(秒)')),
                ('notify_channels', models.JSONField(default=list, help_text='通过集成中心的通知通道编码列表', verbose_name='通知通道')),
                ('notify_groups', models.JSONField(default=list, help_text='通知组 ID 列表', verbose_name='通知组')),
                ('is_template', models.BooleanField(default=False, verbose_name='是否模板')),
                ('source', models.CharField(default='prometheus', help_text='prometheus / influxdb / grafana / manual', max_length=64, verbose_name='数据源类型')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '告警规则',
                'verbose_name_plural': '告警规则',
                'db_table': 'dvadmin_monitor_alert_rule',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('alert_id', models.CharField(help_text='Grafana/Prometheus 告警 ID', max_length=128, unique=True, verbose_name='告警 ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('firing', '触发中'), ('acknowledged', '已确认'), ('resolved', '已恢复'), ('silenced', '已静默'), ('closed', '已关闭')], default='firing', max_length=32, verbose_name='状态')),
                ('severity', models.CharField(choices=[('critical', '严重'), ('warning', '警告'), ('info', '信息')], default='warning', max_length=32, verbose_name='严重级别')),
                ('metric_value', models.FloatField(blank=True, null=True, verbose_name='指标值')),
                ('metric_unit', models.CharField(blank=True, max_length=64, null=True, verbose_name='指标单位')),
                ('labels', models.JSONField(default=dict, verbose_name='标签')),
                ('annotations', models.JSONField(default=dict, verbose_name='注解')),
                ('fired_at', models.DateTimeField(verbose_name='触发时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='恢复时间')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('acknowledged_by', models.CharField(blank=True, max_length=128, null=True, verbose_name='确认人')),
                ('cmdb_host_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='关联主机 ID')),
                ('cmdb_biz_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='关联业务 ID')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='itsm.incident', verbose_name='关联事件工单')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='monitor.alertrule', verbose_name='关联规则')),
            ],
            options={
                'verbose_name': '告警事件',
                'verbose_name_plural': '告警事件',
                'db_table': 'dvadmin_monitor_alert_event',
                'ordering': ['-fired_at'],
            },
        ),
    ]
