# Generated by Django 5.2.15 on 2026-07-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pipeline_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='Pipeline ID'),
        ),
    ]
