# Generated by Django 5.2.15 on 2026-07-09 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_initial'),
        ('itsm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('creator', models.IntegerField(blank=True, db_column='creator_id', help_text='创建人', null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=128, verbose_name='预设名称')),
                ('preset_type', models.CharField(choices=[('user_list', '用户列表'), ('role_list', '角色列表'), ('dept_list', '部门列表'), ('text', '文本'), ('options', '选项列表')], max_length=32, verbose_name='预设类型')),
                ('value', models.JSONField(default=list, verbose_name='预设值')),
                ('sort', models.IntegerField(default=1, verbose_name='排序')),
                ('project', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.PROTECT, to='iam.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '预设管理',
                'verbose_name_plural': '预设管理',
                'db_table': 'opsflow_itsm_preset',
                'ordering': ['sort', '-create_datetime'],
                'unique_together': {('name', 'project')},
            },
        ),
        migrations.AddField(
            model_name='state',
            name='preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='states', to='itsm.preset', verbose_name='关联预设'),
        ),
    ]
