# Generated by Django 5.2.15 on 2026-07-09 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_initial'),
        ('itsm', '0002_preset_state_preset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='iam.project', verbose_name='所属项目'),
        ),
    ]
