# Generated by Django 5.2.15 on 2026-07-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm', '0003_gateway_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='node_key',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='前端节点标识'),
        ),
        migrations.AddField(
            model_name='transition',
            name='from_node_key',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='源节点标识'),
        ),
        migrations.AddField(
            model_name='transition',
            name='to_node_key',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='目标节点标识'),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('workflow', 'node_key')},
        ),
    ]
