# Generated by Django 5.2.15 on 2026-07-10 14:50
# Manually ordered for SLA working time model migration

import django.db.models.deletion
from django.db import migrations, models


def seed_builtin_schedules(apps, schema_editor):
    """Create built-in 5x8 and 7x24 schedules. Idempotent."""
    Duration = apps.get_model('itsm', 'Duration')
    Day = apps.get_model('itsm', 'Day')
    Schedule = apps.get_model('itsm', 'Schedule')

    # 7×24
    d24, _ = Duration.objects.get_or_create(
        name='全天', name_en='All Day',
        defaults={'start_time': '00:00:00', 'end_time': '23:59:59'},
    )
    day_7, _ = Day.objects.get_or_create(
        name='每天', name_en='Every Day',
        defaults={'day_of_week': '0,1,2,3,4,5,6', 'type_of_day': 'NORMAL'},
    )
    day_7.durations.add(d24)
    sched_7x24, _ = Schedule.objects.get_or_create(
        name='7×24', name_en='7×24',
        defaults={'is_builtin': True},
    )
    sched_7x24.days.add(day_7)

    # 5×8
    d_am, _ = Duration.objects.get_or_create(
        name='上午', name_en='Morning',
        defaults={'start_time': '08:00:00', 'end_time': '12:00:00'},
    )
    d_pm, _ = Duration.objects.get_or_create(
        name='下午', name_en='Afternoon',
        defaults={'start_time': '14:00:00', 'end_time': '18:00:00'},
    )
    day_wd, _ = Day.objects.get_or_create(
        name='工作日', name_en='Weekday',
        defaults={'day_of_week': '0,1,2,3,4', 'type_of_day': 'NORMAL'},
    )
    day_wd.durations.add(d_am, d_pm)
    sched_5x8, _ = Schedule.objects.get_or_create(
        name='5×8 标准', name_en='5×8 Standard',
        defaults={'is_builtin': True},
    )
    sched_5x8.days.add(day_wd)


def migrate_existing_policies(apps, schema_editor):
    """Migrate existing SlaPolicy records: assign 7×24 schedule + copy time values."""
    SlaPolicy = apps.get_model('itsm', 'SlaPolicy')
    Schedule = apps.get_model('itsm', 'Schedule')
    try:
        default_schedule = Schedule.objects.get(name='7×24')
    except Schedule.DoesNotExist:
        return

    for policy in SlaPolicy.objects.all():
        policy.schedule = default_schedule
        policy.response_time = policy.response_minutes
        policy.response_unit = 'm'
        policy.resolve_time = policy.resolve_minutes
        policy.resolve_unit = 'm'
        policy.save(update_fields=[
            'schedule', 'response_time', 'response_unit',
            'resolve_time', 'resolve_unit',
        ])


def reverse_policy_migration(apps, schema_editor):
    """Reverse: set schedule to None (fields already removed, so no restore)."""
    SlaPolicy = apps.get_model('itsm', 'SlaPolicy')
    SlaPolicy.objects.all().update(schedule=None)


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_initial'),
        ('itsm', '0004_field_preset'),
    ]

    operations = [
        # 1. Create Duration model
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('creator', models.IntegerField(blank=True, db_column='creator_id', help_text='创建人', null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=128, verbose_name='时段名称')),
                ('name_en', models.CharField(blank=True, default='', max_length=128, verbose_name='时段名称(英文)')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
            ],
            options={
                'verbose_name': '工作时间段',
                'verbose_name_plural': '工作时间段',
                'db_table': 'opsflow_itsm_sla_duration',
                'ordering': ['start_time'],
            },
        ),
        # 2. Create Day model (M2M → Duration)
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('creator', models.IntegerField(blank=True, db_column='creator_id', help_text='创建人', null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=128, verbose_name='日期名称')),
                ('name_en', models.CharField(blank=True, default='', max_length=128, verbose_name='日期名称(英文)')),
                ('day_of_week', models.CharField(default='-1', help_text='Comma-separated weekday indices: 0=Mon,...,6=Sun. Used for NORMAL type.', max_length=32, verbose_name='周几')),
                ('type_of_day', models.CharField(choices=[('NORMAL', '工作日'), ('WORKDAY', '加班日'), ('HOLIDAY', '节假日')], default='NORMAL', max_length=16, verbose_name='日期类型')),
                ('start_date', models.DateField(blank=True, help_text='Date range start for WORKDAY/HOLIDAY types.', null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, help_text='Date range end for WORKDAY/HOLIDAY types.', null=True, verbose_name='结束日期')),
                ('durations', models.ManyToManyField(blank=True, to='itsm.duration', verbose_name='工作时间段')),
            ],
            options={
                'verbose_name': '日期定义',
                'verbose_name_plural': '日期定义',
                'db_table': 'opsflow_itsm_sla_day',
            },
        ),
        # 3. Create Schedule model (M2M → Day × 3)
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('creator', models.IntegerField(blank=True, db_column='creator_id', help_text='创建人', null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=128, verbose_name='排班名称')),
                ('name_en', models.CharField(blank=True, default='', max_length=128, verbose_name='排班名称(英文)')),
                ('is_builtin', models.BooleanField(default=False, help_text='Built-in schedules cannot be deleted.', verbose_name='内置排班')),
                ('days', models.ManyToManyField(blank=True, help_text='NORMAL type days (recurring weekdays).', related_name='schedule_days', to='itsm.day', verbose_name='常规工作日')),
                ('holidays', models.ManyToManyField(blank=True, help_text='HOLIDAY type days (holiday date ranges).', related_name='schedule_holidays', to='itsm.day', verbose_name='节假日')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sla_schedules', to='iam.project', verbose_name='Project')),
                ('workdays', models.ManyToManyField(blank=True, help_text='WORKDAY type days (overtime date ranges).', related_name='schedule_workdays', to='itsm.day', verbose_name='加班日')),
            ],
            options={
                'verbose_name': '排班表',
                'verbose_name_plural': '排班表',
                'db_table': 'opsflow_itsm_sla_schedule',
            },
        ),
        # 4. Seed built-in schedules (5×8 and 7×24)
        migrations.RunPython(seed_builtin_schedules, migrations.RunPython.noop),

        # 5. Add new fields to SlaPolicy (nullable schedule initially)
        migrations.AddField(
            model_name='slapolicy',
            name='schedule',
            field=models.ForeignKey(help_text='Working schedule for working-time-aware SLA calculation.', null=True, on_delete=django.db.models.deletion.PROTECT, to='itsm.schedule', verbose_name='排班表'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='response_time',
            field=models.IntegerField(default=60, verbose_name='响应时限数值'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='response_unit',
            field=models.CharField(choices=[('m', '分钟'), ('h', '小时'), ('d', '天')], default='m', max_length=4, verbose_name='响应时限单位'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='resolve_time',
            field=models.IntegerField(default=480, verbose_name='解决时限数值'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='resolve_unit',
            field=models.CharField(choices=[('m', '分钟'), ('h', '小时'), ('d', '天')], default='m', max_length=4, verbose_name='解决时限单位'),
        ),
        migrations.AddField(
            model_name='slapolicy',
            name='escalation_levels',
            field=models.ManyToManyField(blank=True, help_text='Ordered escalation actions when SLA is violated.', to='itsm.escalationlevel', verbose_name='升级级别'),
        ),

        # 6. Migrate existing policies: map old fields → new fields, assign 7×24 schedule
        migrations.RunPython(migrate_existing_policies, reverse_policy_migration),

        # 7. Drop old fields after data migration
        migrations.RemoveField(
            model_name='slapolicy',
            name='response_minutes',
        ),
        migrations.RemoveField(
            model_name='slapolicy',
            name='resolve_minutes',
        ),

        # 8. Remove old unique constraint, set new unique_together
        migrations.AlterField(
            model_name='slapolicy',
            name='priority',
            field=models.CharField(choices=[('P1', 'P1 危急'), ('P2', 'P2 高'), ('P3', 'P3 中'), ('P4', 'P4 低')], max_length=8, verbose_name='优先级'),
        ),
        migrations.AlterUniqueTogether(
            name='slapolicy',
            unique_together={('priority', 'schedule', 'project')},
        ),

        # 9. Make schedule non-null after data migration is complete
        migrations.AlterField(
            model_name='slapolicy',
            name='schedule',
            field=models.ForeignKey(help_text='Working schedule for working-time-aware SLA calculation.', on_delete=django.db.models.deletion.PROTECT, to='itsm.schedule', verbose_name='排班表'),
        ),

        # 10. Add new fields to SlaTask
        migrations.AddField(
            model_name='slatask',
            name='cost_time',
            field=models.IntegerField(default=0, help_text='Effective SLA working seconds consumed.', verbose_name='已消耗SLA秒数'),
        ),
        migrations.AddField(
            model_name='slatask',
            name='total_seconds',
            field=models.IntegerField(default=0, help_text='Frozen total resolve SLA seconds at task creation.', verbose_name='总SLA秒数'),
        ),
        migrations.AddField(
            model_name='slatask',
            name='begin_at',
            field=models.DateTimeField(blank=True, help_text='When this SLA task actually started counting.', null=True, verbose_name='SLA开始时间'),
        ),
    ]
