# Generated by Django 5.2.15 on 2026-07-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm', '0004_add_node_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatask',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='暂停时间'),
        ),
    ]
