# Generated by Django 5.2.15 on 2026-07-10 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_initial'),
        ('itsm', '0005_sla_working_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day_of_week',
            field=models.CharField(default='-1', help_text='Comma-separated weekday indices: 0=Mon,1=Tue,2=Wed,3=Thu,4=Fri,5=Sat,6=Sun. Used for NORMAL type.', max_length=32, verbose_name='周几'),
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('creator', models.IntegerField(blank=True, db_column='creator_id', help_text='创建人', null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=128, verbose_name='触发器名称')),
                ('name_en', models.CharField(blank=True, default='', max_length=128, verbose_name='触发器名称(英文)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('event_type', models.CharField(choices=[('FLOW_START', '流程开始'), ('FLOW_END', '流程结束'), ('ENTER_STATE', '接入节点'), ('LEAVE_STATE', '离开节点')], max_length=16, verbose_name='事件类型')),
                ('priority', models.CharField(blank=True, choices=[('', '全部'), ('P1', 'P1 危急'), ('P2', 'P2 高'), ('P3', 'P3 中'), ('P4', 'P4 低')], default='', max_length=4, verbose_name='优先级过滤')),
                ('condition', models.JSONField(blank=True, default=dict, help_text='{"logic":"AND","rules":[{"source":"ticket","field":"...","op":"==","value":"..."}]}', verbose_name='字段条件')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itsm_triggers', to='iam.project', verbose_name='Project')),
                ('states', models.ManyToManyField(blank=True, help_text='ENTER_STATE/LEAVE_STATE 时必须指定节点；FLOW_START/FLOW_END 时忽略', related_name='triggers', to='itsm.state', verbose_name='适用节点')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='itsm.workflow', verbose_name='流程模板')),
            ],
            options={
                'verbose_name': '触发器',
                'verbose_name_plural': '触发器',
                'db_table': 'opsflow_itsm_trigger',
            },
        ),
        migrations.CreateModel(
            name='TriggerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='执行顺序')),
                ('action_type', models.CharField(choices=[('NOTIFY', '发送通知'), ('WEBHOOK', 'HTTP 回调'), ('OPSFLOW', '触发运维流程'), ('MODIFY_FIELD', '修改工单字段')], max_length=16, verbose_name='动作类型')),
                ('config', models.JSONField(default=dict, verbose_name='动作配置')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='itsm.trigger', verbose_name='触发器')),
            ],
            options={
                'verbose_name': '触发器动作',
                'verbose_name_plural': '触发器动作',
                'db_table': 'opsflow_itsm_trigger_action',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TriggerExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=16, verbose_name='事件类型')),
                ('status', models.CharField(choices=[('PENDING', '等待执行'), ('SUCCESS', '执行成功'), ('FAILED', '执行失败')], default='PENDING', max_length=8, verbose_name='状态')),
                ('action_results', models.JSONField(default=list, verbose_name='动作执行结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_executions', to='itsm.ticket', verbose_name='工单')),
                ('trigger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='itsm.trigger', verbose_name='触发器')),
            ],
            options={
                'verbose_name': '触发器执行记录',
                'verbose_name_plural': '触发器执行记录',
                'db_table': 'opsflow_itsm_trigger_execution',
                'ordering': ['-created_at'],
            },
        ),
    ]
