# Generated by Django 5.2.15 on 2026-07-05 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_initial'),
        ('itsm', '0005_add_sla_paused_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('creator', models.IntegerField(blank=True, db_column='creator_id', help_text='创建人', null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=128, verbose_name='服务名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='服务描述')),
                ('icon', models.CharField(blank=True, max_length=64, null=True, verbose_name='图标 emoji')),
                ('cover_image', models.CharField(blank=True, max_length=256, null=True, verbose_name='封面图 URL')),
                ('mode', models.CharField(choices=[('flow', '流程驱动'), ('lightweight', '快捷服务')], default='flow', max_length=16, verbose_name='服务模式')),
                ('form_fields', models.JSONField(default=list, verbose_name='自定义表单字段定义')),
                ('visible_to', models.CharField(choices=[('all', '全员'), ('role', '指定角色'), ('user', '指定用户')], default='all', max_length=64, verbose_name='可见范围')),
                ('visible_roles', models.JSONField(default=list, verbose_name='可见角色列表')),
                ('visible_users', models.JSONField(default=list, verbose_name='可见用户列表')),
                ('default_assignee_type', models.CharField(blank=True, default='', max_length=32, verbose_name='快捷服务分派方式')),
                ('default_assignee', models.CharField(blank=True, default='', max_length=128, verbose_name='快捷服务默认处理人')),
                ('expected_duration', models.CharField(blank=True, default='', max_length=64, verbose_name='预计时长')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_items', to='itsm.servicecategory', verbose_name='服务分类')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itsm_service_items', to='iam.project', verbose_name='Project')),
                ('sla_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itsm.slapolicy', verbose_name='SLA 策略')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itsm.workflow', verbose_name='绑定流程（流程驱动模式必选）')),
            ],
            options={
                'verbose_name': '服务项',
                'verbose_name_plural': '服务项',
                'db_table': 'opsflow_itsm_service_item',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
