# Generated by Django 5.2.15 on 2026-07-10 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_initial'),
        ('itsm', '0006_trigger_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('creator', models.IntegerField(blank=True, db_column='creator_id', help_text='创建人', null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=128, verbose_name='模板名称')),
                ('name_en', models.CharField(blank=True, default='', max_length=128, verbose_name='模板名称(英文)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('channels', models.JSONField(default=list, verbose_name='通知渠道')),
                ('title_tpl', models.CharField(blank=True, default='', max_length=500, verbose_name='标题模板')),
                ('body_tpl', models.TextField(blank=True, default='', verbose_name='正文模板')),
                ('receivers', models.JSONField(default=list, verbose_name='接收人')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itsm_notification_templates', to='iam.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': '通知模板',
                'verbose_name_plural': '通知模板',
                'db_table': 'opsflow_itsm_notification_template',
            },
        ),
    ]
