# Generated by Django 5.2.15 on 2026-07-06 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itsm', '0006_add_service_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='auto_assign',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='default_group',
        ),
    ]
