# Generated by Django 5.2.15 on 2026-07-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm', '0007_notification_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerexecution',
            name='max_retries',
            field=models.IntegerField(default=0, verbose_name='最大重试次数'),
        ),
        migrations.AddField(
            model_name='triggerexecution',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下次重试时间'),
        ),
        migrations.AddField(
            model_name='triggerexecution',
            name='retry_count',
            field=models.IntegerField(default=0, verbose_name='已重试次数'),
        ),
        migrations.AddField(
            model_name='triggerexecution',
            name='retry_interval',
            field=models.IntegerField(default=60, verbose_name='重试间隔(秒)'),
        ),
        migrations.AlterField(
            model_name='triggerexecution',
            name='status',
            field=models.CharField(choices=[('PENDING', '等待执行'), ('PROCESSING', '执行中'), ('RETRYING', '重试中'), ('SUCCESS', '执行成功'), ('FAILED', '执行失败')], default='PENDING', max_length=16, verbose_name='状态'),
        ),
    ]
