# Generated by Django 5.2.15 on 2026-07-13 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_initial'),
        ('itsm', '0008_trigger_retry_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FcDesignerSettings',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('creator', models.IntegerField(blank=True, db_column='creator_id', help_text='创建人', null=True, verbose_name='创建人')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('value', models.JSONField(default=dict, verbose_name='设置值')),
                ('business', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='iam.business', verbose_name='所属业务线')),
            ],
            options={
                'verbose_name': '表单设计器设置',
                'verbose_name_plural': '表单设计器设置',
                'db_table': 'opsflow_itsm_fc_designer_settings',
                'unique_together': {('business',)},
            },
        ),
    ]
