# Generated by Django 4.2.7 on 2026-06-04 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDefinition',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('code', models.CharField(help_text='如 biz、host、custom_router', max_length=128, unique=True, verbose_name='模型编码')),
                ('name', models.CharField(help_text='如 业务、主机、自定义路由器', max_length=255, verbose_name='模型名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('icon', models.CharField(blank=True, max_length=128, null=True, verbose_name='图标')),
                ('category', models.CharField(choices=[('business', '业务'), ('cluster', '集群'), ('module', '模块'), ('host', '主机'), ('process', '进程'), ('custom', '自定义')], default='custom', max_length=64, verbose_name='分类')),
                ('is_builtin', models.BooleanField(default=False, help_text='内置模型不可删除', verbose_name='是否内置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '模型定义',
                'verbose_name_plural': '模型定义',
                'db_table': 'dvadmin_cmdb_model_definition',
                'ordering': ['-is_builtin', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModelField',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=255, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=255, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(help_text='英文字段名，如 ip、cpu_cores', max_length=128, verbose_name='字段名')),
                ('label', models.CharField(help_text='如 IP 地址、CPU 核数', max_length=255, verbose_name='显示名')),
                ('field_type', models.CharField(choices=[('string', '字符串'), ('integer', '整数'), ('float', '浮点数'), ('boolean', '布尔'), ('date', '日期'), ('datetime', '日期时间'), ('enum', '枚举'), ('json', 'JSON'), ('ip', 'IP 地址')], default='string', max_length=32, verbose_name='字段类型')),
                ('required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('default_value', models.JSONField(blank=True, null=True, verbose_name='默认值')),
                ('options', models.JSONField(blank=True, help_text='enum 类型时的可选值列表', null=True, verbose_name='枚举选项')),
                ('placeholder', models.CharField(blank=True, max_length=512, null=True, verbose_name='占位提示')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_unique', models.BooleanField(default=False, verbose_name='是否唯一')),
                ('help_text', models.TextField(blank=True, null=True, verbose_name='帮助说明')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('model_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='cmdb.modeldefinition', verbose_name='所属模型')),
            ],
            options={
                'verbose_name': '模型字段',
                'verbose_name_plural': '模型字段',
                'db_table': 'dvadmin_cmdb_model_field',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('model_definition', 'name')},
            },
        ),
    ]
